services:

  postgres:
    image: postgres:15.3
    environment:
      - POSTGRES_USER=root_user
      - POSTGRES_PASSWORD=root_password
      - POSTGRES_DB=voss
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -p 5432" ]
      interval: 2s
      timeout: 10s
      retries: 5

  voss:
    image: eclipse-temurin:21-jre
    ports:
      - 8080:8080
    volumes:
      - ./voss.jar:/app.jar
    command: [ 'java', '-jar', '/app.jar' ]
    healthcheck:
      test: [ "CMD-SHELL", "curl --head -fsS http://localhost:8080/api/v1/data || exit 1" ]
      interval: 2s
      timeout: 10s
      retries: 5

  scheduled-service:
    build:
      context: ./
    environment:
      - DATABASE_HOST=postgres
      - VOSS_HOST=voss
    depends_on:
      voss:
        condition: service_healthy
      postgres:
        condition: service_healthy